SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE
    WHEN status = 'SALE' THEN '판매중'
    WHEN status = 'RESERVED' THEN '예약중'
    WHEN status = 'DONE' THEN '거래완료'
    END `STATUS`
FROM USED_GOODS_BOARD
WHERE DATE_FORMAT(CREATED_DATE,"%Y%m%d") = 20221005
ORDER BY BOARD_ID DESC;